-- ============================================
-- Upgrade embeddings to text-embedding-3-large with 1536 dimensions
-- Note: We use text-embedding-3-large with dimensions parameter set to 1536
-- This gives better quality than text-embedding-3-small while maintaining compatibility with HNSW index
-- HNSW index has a limit of 2000 dimensions, so we can't use full 3072 dimensions
-- ============================================

-- 1. No need to alter column - keeping vector(1536) but using better model
-- ALTER TABLE public.file_chunks ALTER COLUMN embedding TYPE vector(1536);

-- 2. Recreate the vector index (no dimension change needed)
DROP INDEX IF EXISTS idx_file_chunks_embedding;
CREATE INDEX idx_file_chunks_embedding ON public.file_chunks
  USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- 3. Functions remain the same (vector(1536) unchanged)
-- No need to update match_file_chunks and match_user_file_chunks

-- 4. Create embedding cache table with vector(1536)
CREATE TABLE IF NOT EXISTS public.embedding_cache (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  content_hash TEXT NOT NULL UNIQUE,
  embedding vector(1536) NOT NULL,
  model TEXT NOT NULL DEFAULT 'text-embedding-3-large',
  dimensions INT NOT NULL DEFAULT 1536,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Index for fast lookup by hash
CREATE INDEX IF NOT EXISTS idx_embedding_cache_hash ON public.embedding_cache(content_hash);
CREATE INDEX IF NOT EXISTS idx_embedding_cache_model ON public.embedding_cache(model, dimensions);

-- 5. Add new columns to files table for enhanced metadata
ALTER TABLE public.files
  ADD COLUMN IF NOT EXISTS doc_type TEXT,
  ADD COLUMN IF NOT EXISTS doc_summary TEXT,
  ADD COLUMN IF NOT EXISTS doc_importance TEXT CHECK (doc_importance IN ('critical', 'important', 'normal', 'low')),
  ADD COLUMN IF NOT EXISTS doc_department TEXT,
  ADD COLUMN IF NOT EXISTS doc_entities JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS doc_key_dates JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ;

-- 6. Add index for doc_type searches
CREATE INDEX IF NOT EXISTS idx_files_doc_type ON public.files(doc_type);
CREATE INDEX IF NOT EXISTS idx_files_doc_importance ON public.files(doc_importance);
CREATE INDEX IF NOT EXISTS idx_files_doc_department ON public.files(doc_department);

-- 7. RLS policies for embedding_cache
ALTER TABLE public.embedding_cache ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Embedding cache is read-only for all authenticated users"
  ON public.embedding_cache FOR SELECT
  USING (auth.role() = 'authenticated');

CREATE POLICY "Only service role can insert into embedding cache"
  ON public.embedding_cache FOR INSERT
  WITH CHECK (auth.role() = 'service_role');

-- 8. Add comments explaining the migration
COMMENT ON TABLE public.embedding_cache IS 'Cache for OpenAI embeddings to avoid regenerating the same content. Uses text-embedding-3-large with 1536 dimensions (better quality than text-embedding-3-small).';
COMMENT ON COLUMN public.files.doc_type IS 'Document type extracted by LLM analysis (contract, invoice, report, manual, policy, etc.)';
COMMENT ON COLUMN public.files.doc_summary IS 'Executive summary of the document generated by LLM';
COMMENT ON COLUMN public.files.doc_importance IS 'Importance level determined by LLM analysis';

