-- ============================================
-- NETWORK DRIVES ENHANCEMENTS
-- Mejoras M1-M6 para sistema de unidad de red
-- ============================================

-- 1. Add new columns to network_files for LLM analysis (M3)
ALTER TABLE public.network_files
  ADD COLUMN IF NOT EXISTS doc_type TEXT,
  ADD COLUMN IF NOT EXISTS doc_summary TEXT,
  ADD COLUMN IF NOT EXISTS doc_importance TEXT CHECK (doc_importance IN ('critical', 'important', 'normal', 'low')),
  ADD COLUMN IF NOT EXISTS doc_department TEXT,
  ADD COLUMN IF NOT EXISTS doc_entities JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS doc_key_dates JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS analyzed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS priority_score FLOAT DEFAULT 0;

-- 2. Create indexes for fast filtering
CREATE INDEX IF NOT EXISTS idx_network_files_doc_type ON public.network_files(doc_type);
CREATE INDEX IF NOT EXISTS idx_network_files_importance ON public.network_files(doc_importance);
CREATE INDEX IF NOT EXISTS idx_network_files_department ON public.network_files(doc_department);
CREATE INDEX IF NOT EXISTS idx_network_files_priority ON public.network_files(priority_score DESC);
CREATE INDEX IF NOT EXISTS idx_network_files_status ON public.network_files(status);

-- 3. Upgrade embedding dimension for network_file_chunks (M1)
-- Note: The embedding column already exists as vector type, we just need to ensure it's vector(1536)
-- If it was vector(512), we would need to recreate it, but since we're using text-embedding-3-small (1536),
-- it should already be correct. Let's verify and create index.

-- Drop old index if exists
DROP INDEX IF EXISTS idx_network_file_chunks_embedding;

-- Create HNSW index for fast vector search (M1)
CREATE INDEX IF NOT EXISTS idx_network_file_chunks_embedding ON public.network_file_chunks
  USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);

-- 4. Create RPC function for duplicate detection (M6)
CREATE OR REPLACE FUNCTION public.match_network_files_similarity(
  p_drive_id UUID,
  p_query_embedding vector(1536),
  p_match_count INT DEFAULT 5,
  p_similarity_threshold FLOAT DEFAULT 0.95
)
RETURNS TABLE (
  file_id UUID,
  filename TEXT,
  file_path TEXT,
  similarity FLOAT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT ON (nf.id)
    nf.id AS file_id,
    nf.filename,
    nf.file_path,
    1 - (nfc.embedding <=> p_query_embedding) AS similarity
  FROM public.network_file_chunks nfc
  JOIN public.network_files nf ON nf.id = nfc.network_file_id
  WHERE nfc.drive_id = p_drive_id
    AND 1 - (nfc.embedding <=> p_query_embedding) > p_similarity_threshold
  ORDER BY nf.id, nfc.embedding <=> p_query_embedding
  LIMIT p_match_count;
END;
$$;

-- 5. Add comment to document the changes
COMMENT ON TABLE public.network_files IS 'Network drive files with enhanced LLM analysis metadata (M1-M6)';
COMMENT ON COLUMN public.network_files.doc_type IS 'Document type extracted by LLM (M3)';
COMMENT ON COLUMN public.network_files.doc_summary IS 'Executive summary generated by LLM (M3)';
COMMENT ON COLUMN public.network_files.doc_importance IS 'Importance level: critical, important, normal, low (M3)';
COMMENT ON COLUMN public.network_files.doc_department IS 'Department classification (M3)';
COMMENT ON COLUMN public.network_files.doc_entities IS 'Key entities extracted from document (M3)';
COMMENT ON COLUMN public.network_files.doc_key_dates IS 'Important dates found in document (M3)';
COMMENT ON COLUMN public.network_files.priority_score IS 'Calculated priority score for indexing order (M7)';

